-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
-- Version: 2020.2.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hotspot_HW_selectLayer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    temp_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    temp_ce0 : OUT STD_LOGIC;
    temp_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    load_flag : IN STD_LOGIC_VECTOR (0 downto 0);
    center_buf_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_0_ce0 : OUT STD_LOGIC;
    center_buf_0_we0 : OUT STD_LOGIC;
    center_buf_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_1_ce0 : OUT STD_LOGIC;
    center_buf_1_we0 : OUT STD_LOGIC;
    center_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_2_ce0 : OUT STD_LOGIC;
    center_buf_2_we0 : OUT STD_LOGIC;
    center_buf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_3_ce0 : OUT STD_LOGIC;
    center_buf_3_we0 : OUT STD_LOGIC;
    center_buf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_4_ce0 : OUT STD_LOGIC;
    center_buf_4_we0 : OUT STD_LOGIC;
    center_buf_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_5_ce0 : OUT STD_LOGIC;
    center_buf_5_we0 : OUT STD_LOGIC;
    center_buf_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_6_ce0 : OUT STD_LOGIC;
    center_buf_6_we0 : OUT STD_LOGIC;
    center_buf_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_7_ce0 : OUT STD_LOGIC;
    center_buf_7_we0 : OUT STD_LOGIC;
    center_buf_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_8_ce0 : OUT STD_LOGIC;
    center_buf_8_we0 : OUT STD_LOGIC;
    center_buf_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_9_ce0 : OUT STD_LOGIC;
    center_buf_9_we0 : OUT STD_LOGIC;
    center_buf_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_10_ce0 : OUT STD_LOGIC;
    center_buf_10_we0 : OUT STD_LOGIC;
    center_buf_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_11_ce0 : OUT STD_LOGIC;
    center_buf_11_we0 : OUT STD_LOGIC;
    center_buf_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_12_ce0 : OUT STD_LOGIC;
    center_buf_12_we0 : OUT STD_LOGIC;
    center_buf_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_13_ce0 : OUT STD_LOGIC;
    center_buf_13_we0 : OUT STD_LOGIC;
    center_buf_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_14_ce0 : OUT STD_LOGIC;
    center_buf_14_we0 : OUT STD_LOGIC;
    center_buf_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    center_buf_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    center_buf_15_ce0 : OUT STD_LOGIC;
    center_buf_15_we0 : OUT STD_LOGIC;
    center_buf_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_0_ce0 : OUT STD_LOGIC;
    top_buf_0_we0 : OUT STD_LOGIC;
    top_buf_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_1_ce0 : OUT STD_LOGIC;
    top_buf_1_we0 : OUT STD_LOGIC;
    top_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_2_ce0 : OUT STD_LOGIC;
    top_buf_2_we0 : OUT STD_LOGIC;
    top_buf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_3_ce0 : OUT STD_LOGIC;
    top_buf_3_we0 : OUT STD_LOGIC;
    top_buf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_4_ce0 : OUT STD_LOGIC;
    top_buf_4_we0 : OUT STD_LOGIC;
    top_buf_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_5_ce0 : OUT STD_LOGIC;
    top_buf_5_we0 : OUT STD_LOGIC;
    top_buf_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_6_ce0 : OUT STD_LOGIC;
    top_buf_6_we0 : OUT STD_LOGIC;
    top_buf_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_7_ce0 : OUT STD_LOGIC;
    top_buf_7_we0 : OUT STD_LOGIC;
    top_buf_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_8_ce0 : OUT STD_LOGIC;
    top_buf_8_we0 : OUT STD_LOGIC;
    top_buf_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_9_ce0 : OUT STD_LOGIC;
    top_buf_9_we0 : OUT STD_LOGIC;
    top_buf_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_10_ce0 : OUT STD_LOGIC;
    top_buf_10_we0 : OUT STD_LOGIC;
    top_buf_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_11_ce0 : OUT STD_LOGIC;
    top_buf_11_we0 : OUT STD_LOGIC;
    top_buf_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_12_ce0 : OUT STD_LOGIC;
    top_buf_12_we0 : OUT STD_LOGIC;
    top_buf_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_13_ce0 : OUT STD_LOGIC;
    top_buf_13_we0 : OUT STD_LOGIC;
    top_buf_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_14_ce0 : OUT STD_LOGIC;
    top_buf_14_we0 : OUT STD_LOGIC;
    top_buf_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    top_buf_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    top_buf_15_ce0 : OUT STD_LOGIC;
    top_buf_15_we0 : OUT STD_LOGIC;
    top_buf_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_0_ce0 : OUT STD_LOGIC;
    bottom_buf_0_we0 : OUT STD_LOGIC;
    bottom_buf_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_1_ce0 : OUT STD_LOGIC;
    bottom_buf_1_we0 : OUT STD_LOGIC;
    bottom_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_2_ce0 : OUT STD_LOGIC;
    bottom_buf_2_we0 : OUT STD_LOGIC;
    bottom_buf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_3_ce0 : OUT STD_LOGIC;
    bottom_buf_3_we0 : OUT STD_LOGIC;
    bottom_buf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_4_ce0 : OUT STD_LOGIC;
    bottom_buf_4_we0 : OUT STD_LOGIC;
    bottom_buf_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_5_ce0 : OUT STD_LOGIC;
    bottom_buf_5_we0 : OUT STD_LOGIC;
    bottom_buf_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_6_ce0 : OUT STD_LOGIC;
    bottom_buf_6_we0 : OUT STD_LOGIC;
    bottom_buf_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_7_ce0 : OUT STD_LOGIC;
    bottom_buf_7_we0 : OUT STD_LOGIC;
    bottom_buf_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_8_ce0 : OUT STD_LOGIC;
    bottom_buf_8_we0 : OUT STD_LOGIC;
    bottom_buf_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_9_ce0 : OUT STD_LOGIC;
    bottom_buf_9_we0 : OUT STD_LOGIC;
    bottom_buf_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_10_ce0 : OUT STD_LOGIC;
    bottom_buf_10_we0 : OUT STD_LOGIC;
    bottom_buf_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_11_ce0 : OUT STD_LOGIC;
    bottom_buf_11_we0 : OUT STD_LOGIC;
    bottom_buf_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_12_ce0 : OUT STD_LOGIC;
    bottom_buf_12_we0 : OUT STD_LOGIC;
    bottom_buf_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_13_ce0 : OUT STD_LOGIC;
    bottom_buf_13_we0 : OUT STD_LOGIC;
    bottom_buf_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_14_ce0 : OUT STD_LOGIC;
    bottom_buf_14_we0 : OUT STD_LOGIC;
    bottom_buf_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bottom_buf_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bottom_buf_15_ce0 : OUT STD_LOGIC;
    bottom_buf_15_we0 : OUT STD_LOGIC;
    bottom_buf_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    layer : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of hotspot_HW_selectLayer is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv21_1C000 : STD_LOGIC_VECTOR (20 downto 0) := "000011100000000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_18000 : STD_LOGIC_VECTOR (20 downto 0) := "000011000000000000000";
    constant ap_const_lv21_4000 : STD_LOGIC_VECTOR (20 downto 0) := "000000100000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv16_1000 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv17_1F000 : STD_LOGIC_VECTOR (16 downto 0) := "11111000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal zext_ln247_1_fu_259_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln247_1_reg_384 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln248_fu_299_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln248_reg_389 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal select_ln249_fu_354_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln249_reg_394 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln249_1_fu_369_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln249_1_reg_399 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_buffer_load_fu_174_ap_start : STD_LOGIC;
    signal grp_buffer_load_fu_174_ap_done : STD_LOGIC;
    signal grp_buffer_load_fu_174_ap_idle : STD_LOGIC;
    signal grp_buffer_load_fu_174_ap_ready : STD_LOGIC;
    signal grp_buffer_load_fu_174_temp_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_buffer_load_fu_174_temp_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_0_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_0_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_1_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_1_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_2_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_2_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_3_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_3_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_4_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_4_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_4_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_5_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_5_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_5_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_6_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_6_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_6_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_7_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_7_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_7_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_8_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_8_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_8_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_8_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_9_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_9_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_9_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_9_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_10_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_10_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_10_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_10_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_11_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_11_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_11_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_11_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_12_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_12_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_12_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_12_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_13_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_13_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_13_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_13_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_14_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_14_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_14_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_14_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_dest_15_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_buffer_load_fu_174_dest_15_ce0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_15_we0 : STD_LOGIC;
    signal grp_buffer_load_fu_174_dest_15_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_buffer_load_fu_174_source : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_buffer_load_fu_174_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal shl_ln247_1_fu_251_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln_fu_264_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln248_fu_275_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_281_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1_fu_291_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln247_fu_271_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln249_fu_304_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln249_fu_318_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln249_1_fu_324_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln249_fu_334_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln249_1_fu_338_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln249_2_fu_344_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_2_fu_362_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_predicate_op32_call_state6 : BOOLEAN;
    signal ap_block_state6_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hotspot_HW_buffer_load IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        temp_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        load_flag : IN STD_LOGIC_VECTOR (0 downto 0);
        dest_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_0_ce0 : OUT STD_LOGIC;
        dest_0_we0 : OUT STD_LOGIC;
        dest_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_1_ce0 : OUT STD_LOGIC;
        dest_1_we0 : OUT STD_LOGIC;
        dest_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_2_ce0 : OUT STD_LOGIC;
        dest_2_we0 : OUT STD_LOGIC;
        dest_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_3_ce0 : OUT STD_LOGIC;
        dest_3_we0 : OUT STD_LOGIC;
        dest_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_4_ce0 : OUT STD_LOGIC;
        dest_4_we0 : OUT STD_LOGIC;
        dest_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_5_ce0 : OUT STD_LOGIC;
        dest_5_we0 : OUT STD_LOGIC;
        dest_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_6_ce0 : OUT STD_LOGIC;
        dest_6_we0 : OUT STD_LOGIC;
        dest_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_7_ce0 : OUT STD_LOGIC;
        dest_7_we0 : OUT STD_LOGIC;
        dest_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_8_ce0 : OUT STD_LOGIC;
        dest_8_we0 : OUT STD_LOGIC;
        dest_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_9_ce0 : OUT STD_LOGIC;
        dest_9_we0 : OUT STD_LOGIC;
        dest_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_10_ce0 : OUT STD_LOGIC;
        dest_10_we0 : OUT STD_LOGIC;
        dest_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_11_ce0 : OUT STD_LOGIC;
        dest_11_we0 : OUT STD_LOGIC;
        dest_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_12_ce0 : OUT STD_LOGIC;
        dest_12_we0 : OUT STD_LOGIC;
        dest_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_13_ce0 : OUT STD_LOGIC;
        dest_13_we0 : OUT STD_LOGIC;
        dest_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_14_ce0 : OUT STD_LOGIC;
        dest_14_we0 : OUT STD_LOGIC;
        dest_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dest_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dest_15_ce0 : OUT STD_LOGIC;
        dest_15_we0 : OUT STD_LOGIC;
        dest_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        source : IN STD_LOGIC_VECTOR (20 downto 0) );
    end component;



begin
    grp_buffer_load_fu_174 : component hotspot_HW_buffer_load
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_buffer_load_fu_174_ap_start,
        ap_done => grp_buffer_load_fu_174_ap_done,
        ap_idle => grp_buffer_load_fu_174_ap_idle,
        ap_ready => grp_buffer_load_fu_174_ap_ready,
        temp_address0 => grp_buffer_load_fu_174_temp_address0,
        temp_ce0 => grp_buffer_load_fu_174_temp_ce0,
        temp_q0 => temp_q0,
        load_flag => load_flag,
        dest_0_address0 => grp_buffer_load_fu_174_dest_0_address0,
        dest_0_ce0 => grp_buffer_load_fu_174_dest_0_ce0,
        dest_0_we0 => grp_buffer_load_fu_174_dest_0_we0,
        dest_0_d0 => grp_buffer_load_fu_174_dest_0_d0,
        dest_1_address0 => grp_buffer_load_fu_174_dest_1_address0,
        dest_1_ce0 => grp_buffer_load_fu_174_dest_1_ce0,
        dest_1_we0 => grp_buffer_load_fu_174_dest_1_we0,
        dest_1_d0 => grp_buffer_load_fu_174_dest_1_d0,
        dest_2_address0 => grp_buffer_load_fu_174_dest_2_address0,
        dest_2_ce0 => grp_buffer_load_fu_174_dest_2_ce0,
        dest_2_we0 => grp_buffer_load_fu_174_dest_2_we0,
        dest_2_d0 => grp_buffer_load_fu_174_dest_2_d0,
        dest_3_address0 => grp_buffer_load_fu_174_dest_3_address0,
        dest_3_ce0 => grp_buffer_load_fu_174_dest_3_ce0,
        dest_3_we0 => grp_buffer_load_fu_174_dest_3_we0,
        dest_3_d0 => grp_buffer_load_fu_174_dest_3_d0,
        dest_4_address0 => grp_buffer_load_fu_174_dest_4_address0,
        dest_4_ce0 => grp_buffer_load_fu_174_dest_4_ce0,
        dest_4_we0 => grp_buffer_load_fu_174_dest_4_we0,
        dest_4_d0 => grp_buffer_load_fu_174_dest_4_d0,
        dest_5_address0 => grp_buffer_load_fu_174_dest_5_address0,
        dest_5_ce0 => grp_buffer_load_fu_174_dest_5_ce0,
        dest_5_we0 => grp_buffer_load_fu_174_dest_5_we0,
        dest_5_d0 => grp_buffer_load_fu_174_dest_5_d0,
        dest_6_address0 => grp_buffer_load_fu_174_dest_6_address0,
        dest_6_ce0 => grp_buffer_load_fu_174_dest_6_ce0,
        dest_6_we0 => grp_buffer_load_fu_174_dest_6_we0,
        dest_6_d0 => grp_buffer_load_fu_174_dest_6_d0,
        dest_7_address0 => grp_buffer_load_fu_174_dest_7_address0,
        dest_7_ce0 => grp_buffer_load_fu_174_dest_7_ce0,
        dest_7_we0 => grp_buffer_load_fu_174_dest_7_we0,
        dest_7_d0 => grp_buffer_load_fu_174_dest_7_d0,
        dest_8_address0 => grp_buffer_load_fu_174_dest_8_address0,
        dest_8_ce0 => grp_buffer_load_fu_174_dest_8_ce0,
        dest_8_we0 => grp_buffer_load_fu_174_dest_8_we0,
        dest_8_d0 => grp_buffer_load_fu_174_dest_8_d0,
        dest_9_address0 => grp_buffer_load_fu_174_dest_9_address0,
        dest_9_ce0 => grp_buffer_load_fu_174_dest_9_ce0,
        dest_9_we0 => grp_buffer_load_fu_174_dest_9_we0,
        dest_9_d0 => grp_buffer_load_fu_174_dest_9_d0,
        dest_10_address0 => grp_buffer_load_fu_174_dest_10_address0,
        dest_10_ce0 => grp_buffer_load_fu_174_dest_10_ce0,
        dest_10_we0 => grp_buffer_load_fu_174_dest_10_we0,
        dest_10_d0 => grp_buffer_load_fu_174_dest_10_d0,
        dest_11_address0 => grp_buffer_load_fu_174_dest_11_address0,
        dest_11_ce0 => grp_buffer_load_fu_174_dest_11_ce0,
        dest_11_we0 => grp_buffer_load_fu_174_dest_11_we0,
        dest_11_d0 => grp_buffer_load_fu_174_dest_11_d0,
        dest_12_address0 => grp_buffer_load_fu_174_dest_12_address0,
        dest_12_ce0 => grp_buffer_load_fu_174_dest_12_ce0,
        dest_12_we0 => grp_buffer_load_fu_174_dest_12_we0,
        dest_12_d0 => grp_buffer_load_fu_174_dest_12_d0,
        dest_13_address0 => grp_buffer_load_fu_174_dest_13_address0,
        dest_13_ce0 => grp_buffer_load_fu_174_dest_13_ce0,
        dest_13_we0 => grp_buffer_load_fu_174_dest_13_we0,
        dest_13_d0 => grp_buffer_load_fu_174_dest_13_d0,
        dest_14_address0 => grp_buffer_load_fu_174_dest_14_address0,
        dest_14_ce0 => grp_buffer_load_fu_174_dest_14_ce0,
        dest_14_we0 => grp_buffer_load_fu_174_dest_14_we0,
        dest_14_d0 => grp_buffer_load_fu_174_dest_14_d0,
        dest_15_address0 => grp_buffer_load_fu_174_dest_15_address0,
        dest_15_ce0 => grp_buffer_load_fu_174_dest_15_ce0,
        dest_15_we0 => grp_buffer_load_fu_174_dest_15_we0,
        dest_15_d0 => grp_buffer_load_fu_174_dest_15_d0,
        source => grp_buffer_load_fu_174_source);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_buffer_load_fu_174_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_buffer_load_fu_174_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or (not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                    grp_buffer_load_fu_174_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_buffer_load_fu_174_ap_ready = ap_const_logic_1)) then 
                    grp_buffer_load_fu_174_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                    select_ln249_reg_394(12 downto 8) <= select_ln249_fu_354_p3(12 downto 8);
                    zext_ln248_reg_389(17 downto 14) <= zext_ln248_fu_299_p1(17 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                    sext_ln249_1_reg_399(20 downto 14) <= sext_ln249_1_fu_369_p1(20 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    zext_ln247_1_reg_384(17 downto 14) <= zext_ln247_1_fu_259_p1(17 downto 14);
            end if;
        end if;
    end process;
    zext_ln247_1_reg_384(13 downto 0) <= "00000000000000";
    zext_ln247_1_reg_384(20 downto 18) <= "000";
    zext_ln248_reg_389(13 downto 0) <= "00000000000000";
    zext_ln248_reg_389(20 downto 18) <= "000";
    select_ln249_reg_394(7 downto 0) <= "00000000";
    sext_ln249_1_reg_399(13 downto 0) <= "00000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, layer, grp_buffer_load_fu_174_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state13, ap_block_state6_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif (((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_buffer_load_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_buffer_load_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((grp_buffer_load_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_buffer_load_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state11 => 
                if (((grp_buffer_load_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((grp_buffer_load_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln248_fu_275_p2 <= std_logic_vector(unsigned(shl_ln_fu_264_p3) + unsigned(ap_const_lv16_1000));
    add_ln249_fu_304_p2 <= std_logic_vector(unsigned(zext_ln247_fu_271_p1) + unsigned(ap_const_lv17_1F000));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state6_on_subcall_done_assign_proc : process(layer, grp_buffer_load_fu_174_ap_done, ap_predicate_op32_call_state6)
    begin
                ap_block_state6_on_subcall_done <= (((ap_predicate_op32_call_state6 = ap_const_boolean_1) and (grp_buffer_load_fu_174_ap_done = ap_const_logic_0)) or ((grp_buffer_load_fu_174_ap_done = ap_const_logic_0) and (layer = ap_const_lv4_7)) or ((grp_buffer_load_fu_174_ap_done = ap_const_logic_0) and (layer = ap_const_lv4_0)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        if ((((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op32_call_state6_assign_proc : process(layer)
    begin
                ap_predicate_op32_call_state6 <= (not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_0_address0 <= grp_buffer_load_fu_174_dest_0_address0;

    bottom_buf_0_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_0_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_0_ce0 <= grp_buffer_load_fu_174_dest_0_ce0;
        else 
            bottom_buf_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_0_d0 <= grp_buffer_load_fu_174_dest_0_d0;

    bottom_buf_0_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_0_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_0_we0 <= grp_buffer_load_fu_174_dest_0_we0;
        else 
            bottom_buf_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_10_address0 <= grp_buffer_load_fu_174_dest_10_address0;

    bottom_buf_10_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_10_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_10_ce0 <= grp_buffer_load_fu_174_dest_10_ce0;
        else 
            bottom_buf_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_10_d0 <= grp_buffer_load_fu_174_dest_10_d0;

    bottom_buf_10_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_10_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_10_we0 <= grp_buffer_load_fu_174_dest_10_we0;
        else 
            bottom_buf_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_11_address0 <= grp_buffer_load_fu_174_dest_11_address0;

    bottom_buf_11_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_11_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_11_ce0 <= grp_buffer_load_fu_174_dest_11_ce0;
        else 
            bottom_buf_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_11_d0 <= grp_buffer_load_fu_174_dest_11_d0;

    bottom_buf_11_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_11_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_11_we0 <= grp_buffer_load_fu_174_dest_11_we0;
        else 
            bottom_buf_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_12_address0 <= grp_buffer_load_fu_174_dest_12_address0;

    bottom_buf_12_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_12_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_12_ce0 <= grp_buffer_load_fu_174_dest_12_ce0;
        else 
            bottom_buf_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_12_d0 <= grp_buffer_load_fu_174_dest_12_d0;

    bottom_buf_12_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_12_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_12_we0 <= grp_buffer_load_fu_174_dest_12_we0;
        else 
            bottom_buf_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_13_address0 <= grp_buffer_load_fu_174_dest_13_address0;

    bottom_buf_13_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_13_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_13_ce0 <= grp_buffer_load_fu_174_dest_13_ce0;
        else 
            bottom_buf_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_13_d0 <= grp_buffer_load_fu_174_dest_13_d0;

    bottom_buf_13_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_13_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_13_we0 <= grp_buffer_load_fu_174_dest_13_we0;
        else 
            bottom_buf_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_14_address0 <= grp_buffer_load_fu_174_dest_14_address0;

    bottom_buf_14_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_14_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_14_ce0 <= grp_buffer_load_fu_174_dest_14_ce0;
        else 
            bottom_buf_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_14_d0 <= grp_buffer_load_fu_174_dest_14_d0;

    bottom_buf_14_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_14_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_14_we0 <= grp_buffer_load_fu_174_dest_14_we0;
        else 
            bottom_buf_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_15_address0 <= grp_buffer_load_fu_174_dest_15_address0;

    bottom_buf_15_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_15_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_15_ce0 <= grp_buffer_load_fu_174_dest_15_ce0;
        else 
            bottom_buf_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_15_d0 <= grp_buffer_load_fu_174_dest_15_d0;

    bottom_buf_15_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_15_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_15_we0 <= grp_buffer_load_fu_174_dest_15_we0;
        else 
            bottom_buf_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_1_address0 <= grp_buffer_load_fu_174_dest_1_address0;

    bottom_buf_1_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_1_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_1_ce0 <= grp_buffer_load_fu_174_dest_1_ce0;
        else 
            bottom_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_1_d0 <= grp_buffer_load_fu_174_dest_1_d0;

    bottom_buf_1_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_1_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_1_we0 <= grp_buffer_load_fu_174_dest_1_we0;
        else 
            bottom_buf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_2_address0 <= grp_buffer_load_fu_174_dest_2_address0;

    bottom_buf_2_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_2_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_2_ce0 <= grp_buffer_load_fu_174_dest_2_ce0;
        else 
            bottom_buf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_2_d0 <= grp_buffer_load_fu_174_dest_2_d0;

    bottom_buf_2_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_2_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_2_we0 <= grp_buffer_load_fu_174_dest_2_we0;
        else 
            bottom_buf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_3_address0 <= grp_buffer_load_fu_174_dest_3_address0;

    bottom_buf_3_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_3_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_3_ce0 <= grp_buffer_load_fu_174_dest_3_ce0;
        else 
            bottom_buf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_3_d0 <= grp_buffer_load_fu_174_dest_3_d0;

    bottom_buf_3_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_3_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_3_we0 <= grp_buffer_load_fu_174_dest_3_we0;
        else 
            bottom_buf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_4_address0 <= grp_buffer_load_fu_174_dest_4_address0;

    bottom_buf_4_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_4_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_4_ce0 <= grp_buffer_load_fu_174_dest_4_ce0;
        else 
            bottom_buf_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_4_d0 <= grp_buffer_load_fu_174_dest_4_d0;

    bottom_buf_4_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_4_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_4_we0 <= grp_buffer_load_fu_174_dest_4_we0;
        else 
            bottom_buf_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_5_address0 <= grp_buffer_load_fu_174_dest_5_address0;

    bottom_buf_5_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_5_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_5_ce0 <= grp_buffer_load_fu_174_dest_5_ce0;
        else 
            bottom_buf_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_5_d0 <= grp_buffer_load_fu_174_dest_5_d0;

    bottom_buf_5_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_5_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_5_we0 <= grp_buffer_load_fu_174_dest_5_we0;
        else 
            bottom_buf_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_6_address0 <= grp_buffer_load_fu_174_dest_6_address0;

    bottom_buf_6_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_6_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_6_ce0 <= grp_buffer_load_fu_174_dest_6_ce0;
        else 
            bottom_buf_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_6_d0 <= grp_buffer_load_fu_174_dest_6_d0;

    bottom_buf_6_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_6_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_6_we0 <= grp_buffer_load_fu_174_dest_6_we0;
        else 
            bottom_buf_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_7_address0 <= grp_buffer_load_fu_174_dest_7_address0;

    bottom_buf_7_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_7_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_7_ce0 <= grp_buffer_load_fu_174_dest_7_ce0;
        else 
            bottom_buf_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_7_d0 <= grp_buffer_load_fu_174_dest_7_d0;

    bottom_buf_7_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_7_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_7_we0 <= grp_buffer_load_fu_174_dest_7_we0;
        else 
            bottom_buf_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_8_address0 <= grp_buffer_load_fu_174_dest_8_address0;

    bottom_buf_8_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_8_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_8_ce0 <= grp_buffer_load_fu_174_dest_8_ce0;
        else 
            bottom_buf_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_8_d0 <= grp_buffer_load_fu_174_dest_8_d0;

    bottom_buf_8_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_8_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_8_we0 <= grp_buffer_load_fu_174_dest_8_we0;
        else 
            bottom_buf_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_9_address0 <= grp_buffer_load_fu_174_dest_9_address0;

    bottom_buf_9_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_9_ce0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_9_ce0 <= grp_buffer_load_fu_174_dest_9_ce0;
        else 
            bottom_buf_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bottom_buf_9_d0 <= grp_buffer_load_fu_174_dest_9_d0;

    bottom_buf_9_we0_assign_proc : process(layer, grp_buffer_load_fu_174_dest_9_we0, ap_CS_fsm_state6)
    begin
        if (((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bottom_buf_9_we0 <= grp_buffer_load_fu_174_dest_9_we0;
        else 
            bottom_buf_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_0_address0 <= grp_buffer_load_fu_174_dest_0_address0;

    center_buf_0_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_0_ce0 <= grp_buffer_load_fu_174_dest_0_ce0;
        else 
            center_buf_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_0_d0 <= grp_buffer_load_fu_174_dest_0_d0;

    center_buf_0_we0_assign_proc : process(grp_buffer_load_fu_174_dest_0_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_0_we0 <= grp_buffer_load_fu_174_dest_0_we0;
        else 
            center_buf_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_10_address0 <= grp_buffer_load_fu_174_dest_10_address0;

    center_buf_10_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_10_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_10_ce0 <= grp_buffer_load_fu_174_dest_10_ce0;
        else 
            center_buf_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_10_d0 <= grp_buffer_load_fu_174_dest_10_d0;

    center_buf_10_we0_assign_proc : process(grp_buffer_load_fu_174_dest_10_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_10_we0 <= grp_buffer_load_fu_174_dest_10_we0;
        else 
            center_buf_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_11_address0 <= grp_buffer_load_fu_174_dest_11_address0;

    center_buf_11_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_11_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_11_ce0 <= grp_buffer_load_fu_174_dest_11_ce0;
        else 
            center_buf_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_11_d0 <= grp_buffer_load_fu_174_dest_11_d0;

    center_buf_11_we0_assign_proc : process(grp_buffer_load_fu_174_dest_11_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_11_we0 <= grp_buffer_load_fu_174_dest_11_we0;
        else 
            center_buf_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_12_address0 <= grp_buffer_load_fu_174_dest_12_address0;

    center_buf_12_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_12_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_12_ce0 <= grp_buffer_load_fu_174_dest_12_ce0;
        else 
            center_buf_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_12_d0 <= grp_buffer_load_fu_174_dest_12_d0;

    center_buf_12_we0_assign_proc : process(grp_buffer_load_fu_174_dest_12_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_12_we0 <= grp_buffer_load_fu_174_dest_12_we0;
        else 
            center_buf_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_13_address0 <= grp_buffer_load_fu_174_dest_13_address0;

    center_buf_13_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_13_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_13_ce0 <= grp_buffer_load_fu_174_dest_13_ce0;
        else 
            center_buf_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_13_d0 <= grp_buffer_load_fu_174_dest_13_d0;

    center_buf_13_we0_assign_proc : process(grp_buffer_load_fu_174_dest_13_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_13_we0 <= grp_buffer_load_fu_174_dest_13_we0;
        else 
            center_buf_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_14_address0 <= grp_buffer_load_fu_174_dest_14_address0;

    center_buf_14_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_14_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_14_ce0 <= grp_buffer_load_fu_174_dest_14_ce0;
        else 
            center_buf_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_14_d0 <= grp_buffer_load_fu_174_dest_14_d0;

    center_buf_14_we0_assign_proc : process(grp_buffer_load_fu_174_dest_14_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_14_we0 <= grp_buffer_load_fu_174_dest_14_we0;
        else 
            center_buf_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_15_address0 <= grp_buffer_load_fu_174_dest_15_address0;

    center_buf_15_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_15_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_15_ce0 <= grp_buffer_load_fu_174_dest_15_ce0;
        else 
            center_buf_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_15_d0 <= grp_buffer_load_fu_174_dest_15_d0;

    center_buf_15_we0_assign_proc : process(grp_buffer_load_fu_174_dest_15_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_15_we0 <= grp_buffer_load_fu_174_dest_15_we0;
        else 
            center_buf_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_1_address0 <= grp_buffer_load_fu_174_dest_1_address0;

    center_buf_1_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_1_ce0 <= grp_buffer_load_fu_174_dest_1_ce0;
        else 
            center_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_1_d0 <= grp_buffer_load_fu_174_dest_1_d0;

    center_buf_1_we0_assign_proc : process(grp_buffer_load_fu_174_dest_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_1_we0 <= grp_buffer_load_fu_174_dest_1_we0;
        else 
            center_buf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_2_address0 <= grp_buffer_load_fu_174_dest_2_address0;

    center_buf_2_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_2_ce0 <= grp_buffer_load_fu_174_dest_2_ce0;
        else 
            center_buf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_2_d0 <= grp_buffer_load_fu_174_dest_2_d0;

    center_buf_2_we0_assign_proc : process(grp_buffer_load_fu_174_dest_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_2_we0 <= grp_buffer_load_fu_174_dest_2_we0;
        else 
            center_buf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_3_address0 <= grp_buffer_load_fu_174_dest_3_address0;

    center_buf_3_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_3_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_3_ce0 <= grp_buffer_load_fu_174_dest_3_ce0;
        else 
            center_buf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_3_d0 <= grp_buffer_load_fu_174_dest_3_d0;

    center_buf_3_we0_assign_proc : process(grp_buffer_load_fu_174_dest_3_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_3_we0 <= grp_buffer_load_fu_174_dest_3_we0;
        else 
            center_buf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_4_address0 <= grp_buffer_load_fu_174_dest_4_address0;

    center_buf_4_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_4_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_4_ce0 <= grp_buffer_load_fu_174_dest_4_ce0;
        else 
            center_buf_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_4_d0 <= grp_buffer_load_fu_174_dest_4_d0;

    center_buf_4_we0_assign_proc : process(grp_buffer_load_fu_174_dest_4_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_4_we0 <= grp_buffer_load_fu_174_dest_4_we0;
        else 
            center_buf_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_5_address0 <= grp_buffer_load_fu_174_dest_5_address0;

    center_buf_5_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_5_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_5_ce0 <= grp_buffer_load_fu_174_dest_5_ce0;
        else 
            center_buf_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_5_d0 <= grp_buffer_load_fu_174_dest_5_d0;

    center_buf_5_we0_assign_proc : process(grp_buffer_load_fu_174_dest_5_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_5_we0 <= grp_buffer_load_fu_174_dest_5_we0;
        else 
            center_buf_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_6_address0 <= grp_buffer_load_fu_174_dest_6_address0;

    center_buf_6_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_6_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_6_ce0 <= grp_buffer_load_fu_174_dest_6_ce0;
        else 
            center_buf_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_6_d0 <= grp_buffer_load_fu_174_dest_6_d0;

    center_buf_6_we0_assign_proc : process(grp_buffer_load_fu_174_dest_6_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_6_we0 <= grp_buffer_load_fu_174_dest_6_we0;
        else 
            center_buf_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_7_address0 <= grp_buffer_load_fu_174_dest_7_address0;

    center_buf_7_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_7_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_7_ce0 <= grp_buffer_load_fu_174_dest_7_ce0;
        else 
            center_buf_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_7_d0 <= grp_buffer_load_fu_174_dest_7_d0;

    center_buf_7_we0_assign_proc : process(grp_buffer_load_fu_174_dest_7_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_7_we0 <= grp_buffer_load_fu_174_dest_7_we0;
        else 
            center_buf_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_8_address0 <= grp_buffer_load_fu_174_dest_8_address0;

    center_buf_8_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_8_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_8_ce0 <= grp_buffer_load_fu_174_dest_8_ce0;
        else 
            center_buf_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_8_d0 <= grp_buffer_load_fu_174_dest_8_d0;

    center_buf_8_we0_assign_proc : process(grp_buffer_load_fu_174_dest_8_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_8_we0 <= grp_buffer_load_fu_174_dest_8_we0;
        else 
            center_buf_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_9_address0 <= grp_buffer_load_fu_174_dest_9_address0;

    center_buf_9_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_9_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_9_ce0 <= grp_buffer_load_fu_174_dest_9_ce0;
        else 
            center_buf_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    center_buf_9_d0 <= grp_buffer_load_fu_174_dest_9_d0;

    center_buf_9_we0_assign_proc : process(grp_buffer_load_fu_174_dest_9_we0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            center_buf_9_we0 <= grp_buffer_load_fu_174_dest_9_we0;
        else 
            center_buf_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_buffer_load_fu_174_ap_start <= grp_buffer_load_fu_174_ap_start_reg;

    grp_buffer_load_fu_174_source_assign_proc : process(layer, zext_ln247_1_reg_384, zext_ln248_reg_389, sext_ln249_1_reg_399, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if ((not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_buffer_load_fu_174_source <= sext_ln249_1_reg_399;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_buffer_load_fu_174_source <= zext_ln248_reg_389;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_buffer_load_fu_174_source <= ap_const_lv21_4000;
        elsif (((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_buffer_load_fu_174_source <= ap_const_lv21_18000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_buffer_load_fu_174_source <= zext_ln247_1_reg_384;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            grp_buffer_load_fu_174_source <= ap_const_lv21_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_buffer_load_fu_174_source <= ap_const_lv21_1C000;
        else 
            grp_buffer_load_fu_174_source <= "XXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    select_ln249_fu_354_p3 <= 
        sub_ln249_1_fu_338_p2 when (tmp_1_fu_310_p3(0) = '1') else 
        trunc_ln249_2_fu_344_p4;
        sext_ln249_1_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_362_p3),21));

        sext_ln249_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln249_1_fu_324_p4),13));

    shl_ln1_fu_291_p3 <= (tmp_fu_281_p4 & ap_const_lv6_0);
    shl_ln247_1_fu_251_p3 <= (layer & ap_const_lv14_0);
    shl_ln_fu_264_p3 <= (layer & ap_const_lv12_0);
    sub_ln249_1_fu_338_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(sext_ln249_fu_334_p1));
    sub_ln249_fu_318_p2 <= std_logic_vector(unsigned(ap_const_lv16_1000) - unsigned(shl_ln_fu_264_p3));
    temp_address0 <= grp_buffer_load_fu_174_temp_address0;

    temp_ce0_assign_proc : process(layer, grp_buffer_load_fu_174_temp_ce0, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state11, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not((layer = ap_const_lv4_7)) and not((layer = ap_const_lv4_0)) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((layer = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            temp_ce0 <= grp_buffer_load_fu_174_temp_ce0;
        else 
            temp_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_310_p3 <= add_ln249_fu_304_p2(16 downto 16);
    tmp_2_fu_362_p3 <= (select_ln249_reg_394 & ap_const_lv6_0);
    tmp_fu_281_p4 <= add_ln248_fu_275_p2(15 downto 4);
    top_buf_0_address0 <= grp_buffer_load_fu_174_dest_0_address0;

    top_buf_0_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_0_ce0 <= grp_buffer_load_fu_174_dest_0_ce0;
        else 
            top_buf_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_0_d0 <= grp_buffer_load_fu_174_dest_0_d0;

    top_buf_0_we0_assign_proc : process(grp_buffer_load_fu_174_dest_0_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_0_we0 <= grp_buffer_load_fu_174_dest_0_we0;
        else 
            top_buf_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_10_address0 <= grp_buffer_load_fu_174_dest_10_address0;

    top_buf_10_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_10_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_10_ce0 <= grp_buffer_load_fu_174_dest_10_ce0;
        else 
            top_buf_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_10_d0 <= grp_buffer_load_fu_174_dest_10_d0;

    top_buf_10_we0_assign_proc : process(grp_buffer_load_fu_174_dest_10_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_10_we0 <= grp_buffer_load_fu_174_dest_10_we0;
        else 
            top_buf_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_11_address0 <= grp_buffer_load_fu_174_dest_11_address0;

    top_buf_11_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_11_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_11_ce0 <= grp_buffer_load_fu_174_dest_11_ce0;
        else 
            top_buf_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_11_d0 <= grp_buffer_load_fu_174_dest_11_d0;

    top_buf_11_we0_assign_proc : process(grp_buffer_load_fu_174_dest_11_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_11_we0 <= grp_buffer_load_fu_174_dest_11_we0;
        else 
            top_buf_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_12_address0 <= grp_buffer_load_fu_174_dest_12_address0;

    top_buf_12_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_12_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_12_ce0 <= grp_buffer_load_fu_174_dest_12_ce0;
        else 
            top_buf_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_12_d0 <= grp_buffer_load_fu_174_dest_12_d0;

    top_buf_12_we0_assign_proc : process(grp_buffer_load_fu_174_dest_12_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_12_we0 <= grp_buffer_load_fu_174_dest_12_we0;
        else 
            top_buf_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_13_address0 <= grp_buffer_load_fu_174_dest_13_address0;

    top_buf_13_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_13_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_13_ce0 <= grp_buffer_load_fu_174_dest_13_ce0;
        else 
            top_buf_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_13_d0 <= grp_buffer_load_fu_174_dest_13_d0;

    top_buf_13_we0_assign_proc : process(grp_buffer_load_fu_174_dest_13_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_13_we0 <= grp_buffer_load_fu_174_dest_13_we0;
        else 
            top_buf_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_14_address0 <= grp_buffer_load_fu_174_dest_14_address0;

    top_buf_14_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_14_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_14_ce0 <= grp_buffer_load_fu_174_dest_14_ce0;
        else 
            top_buf_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_14_d0 <= grp_buffer_load_fu_174_dest_14_d0;

    top_buf_14_we0_assign_proc : process(grp_buffer_load_fu_174_dest_14_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_14_we0 <= grp_buffer_load_fu_174_dest_14_we0;
        else 
            top_buf_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_15_address0 <= grp_buffer_load_fu_174_dest_15_address0;

    top_buf_15_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_15_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_15_ce0 <= grp_buffer_load_fu_174_dest_15_ce0;
        else 
            top_buf_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_15_d0 <= grp_buffer_load_fu_174_dest_15_d0;

    top_buf_15_we0_assign_proc : process(grp_buffer_load_fu_174_dest_15_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_15_we0 <= grp_buffer_load_fu_174_dest_15_we0;
        else 
            top_buf_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_1_address0 <= grp_buffer_load_fu_174_dest_1_address0;

    top_buf_1_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_1_ce0 <= grp_buffer_load_fu_174_dest_1_ce0;
        else 
            top_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_1_d0 <= grp_buffer_load_fu_174_dest_1_d0;

    top_buf_1_we0_assign_proc : process(grp_buffer_load_fu_174_dest_1_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_1_we0 <= grp_buffer_load_fu_174_dest_1_we0;
        else 
            top_buf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_2_address0 <= grp_buffer_load_fu_174_dest_2_address0;

    top_buf_2_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_2_ce0 <= grp_buffer_load_fu_174_dest_2_ce0;
        else 
            top_buf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_2_d0 <= grp_buffer_load_fu_174_dest_2_d0;

    top_buf_2_we0_assign_proc : process(grp_buffer_load_fu_174_dest_2_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_2_we0 <= grp_buffer_load_fu_174_dest_2_we0;
        else 
            top_buf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_3_address0 <= grp_buffer_load_fu_174_dest_3_address0;

    top_buf_3_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_3_ce0 <= grp_buffer_load_fu_174_dest_3_ce0;
        else 
            top_buf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_3_d0 <= grp_buffer_load_fu_174_dest_3_d0;

    top_buf_3_we0_assign_proc : process(grp_buffer_load_fu_174_dest_3_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_3_we0 <= grp_buffer_load_fu_174_dest_3_we0;
        else 
            top_buf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_4_address0 <= grp_buffer_load_fu_174_dest_4_address0;

    top_buf_4_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_4_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_4_ce0 <= grp_buffer_load_fu_174_dest_4_ce0;
        else 
            top_buf_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_4_d0 <= grp_buffer_load_fu_174_dest_4_d0;

    top_buf_4_we0_assign_proc : process(grp_buffer_load_fu_174_dest_4_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_4_we0 <= grp_buffer_load_fu_174_dest_4_we0;
        else 
            top_buf_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_5_address0 <= grp_buffer_load_fu_174_dest_5_address0;

    top_buf_5_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_5_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_5_ce0 <= grp_buffer_load_fu_174_dest_5_ce0;
        else 
            top_buf_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_5_d0 <= grp_buffer_load_fu_174_dest_5_d0;

    top_buf_5_we0_assign_proc : process(grp_buffer_load_fu_174_dest_5_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_5_we0 <= grp_buffer_load_fu_174_dest_5_we0;
        else 
            top_buf_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_6_address0 <= grp_buffer_load_fu_174_dest_6_address0;

    top_buf_6_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_6_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_6_ce0 <= grp_buffer_load_fu_174_dest_6_ce0;
        else 
            top_buf_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_6_d0 <= grp_buffer_load_fu_174_dest_6_d0;

    top_buf_6_we0_assign_proc : process(grp_buffer_load_fu_174_dest_6_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_6_we0 <= grp_buffer_load_fu_174_dest_6_we0;
        else 
            top_buf_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_7_address0 <= grp_buffer_load_fu_174_dest_7_address0;

    top_buf_7_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_7_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_7_ce0 <= grp_buffer_load_fu_174_dest_7_ce0;
        else 
            top_buf_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_7_d0 <= grp_buffer_load_fu_174_dest_7_d0;

    top_buf_7_we0_assign_proc : process(grp_buffer_load_fu_174_dest_7_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_7_we0 <= grp_buffer_load_fu_174_dest_7_we0;
        else 
            top_buf_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_8_address0 <= grp_buffer_load_fu_174_dest_8_address0;

    top_buf_8_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_8_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_8_ce0 <= grp_buffer_load_fu_174_dest_8_ce0;
        else 
            top_buf_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_8_d0 <= grp_buffer_load_fu_174_dest_8_d0;

    top_buf_8_we0_assign_proc : process(grp_buffer_load_fu_174_dest_8_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_8_we0 <= grp_buffer_load_fu_174_dest_8_we0;
        else 
            top_buf_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_9_address0 <= grp_buffer_load_fu_174_dest_9_address0;

    top_buf_9_ce0_assign_proc : process(grp_buffer_load_fu_174_dest_9_ce0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_9_ce0 <= grp_buffer_load_fu_174_dest_9_ce0;
        else 
            top_buf_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_buf_9_d0 <= grp_buffer_load_fu_174_dest_9_d0;

    top_buf_9_we0_assign_proc : process(grp_buffer_load_fu_174_dest_9_we0, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            top_buf_9_we0 <= grp_buffer_load_fu_174_dest_9_we0;
        else 
            top_buf_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln249_1_fu_324_p4 <= sub_ln249_fu_318_p2(15 downto 4);
    trunc_ln249_2_fu_344_p4 <= add_ln249_fu_304_p2(16 downto 4);
    zext_ln247_1_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln247_1_fu_251_p3),21));
    zext_ln247_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_264_p3),17));
    zext_ln248_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_291_p3),21));
end behav;
