// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
// Version: 2020.2.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hotspot_HW_selectLayer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_address0,
        temp_ce0,
        temp_q0,
        load_flag,
        center_buf_0_address0,
        center_buf_0_ce0,
        center_buf_0_we0,
        center_buf_0_d0,
        center_buf_1_address0,
        center_buf_1_ce0,
        center_buf_1_we0,
        center_buf_1_d0,
        center_buf_2_address0,
        center_buf_2_ce0,
        center_buf_2_we0,
        center_buf_2_d0,
        center_buf_3_address0,
        center_buf_3_ce0,
        center_buf_3_we0,
        center_buf_3_d0,
        center_buf_4_address0,
        center_buf_4_ce0,
        center_buf_4_we0,
        center_buf_4_d0,
        center_buf_5_address0,
        center_buf_5_ce0,
        center_buf_5_we0,
        center_buf_5_d0,
        center_buf_6_address0,
        center_buf_6_ce0,
        center_buf_6_we0,
        center_buf_6_d0,
        center_buf_7_address0,
        center_buf_7_ce0,
        center_buf_7_we0,
        center_buf_7_d0,
        center_buf_8_address0,
        center_buf_8_ce0,
        center_buf_8_we0,
        center_buf_8_d0,
        center_buf_9_address0,
        center_buf_9_ce0,
        center_buf_9_we0,
        center_buf_9_d0,
        center_buf_10_address0,
        center_buf_10_ce0,
        center_buf_10_we0,
        center_buf_10_d0,
        center_buf_11_address0,
        center_buf_11_ce0,
        center_buf_11_we0,
        center_buf_11_d0,
        center_buf_12_address0,
        center_buf_12_ce0,
        center_buf_12_we0,
        center_buf_12_d0,
        center_buf_13_address0,
        center_buf_13_ce0,
        center_buf_13_we0,
        center_buf_13_d0,
        center_buf_14_address0,
        center_buf_14_ce0,
        center_buf_14_we0,
        center_buf_14_d0,
        center_buf_15_address0,
        center_buf_15_ce0,
        center_buf_15_we0,
        center_buf_15_d0,
        top_buf_0_address0,
        top_buf_0_ce0,
        top_buf_0_we0,
        top_buf_0_d0,
        top_buf_1_address0,
        top_buf_1_ce0,
        top_buf_1_we0,
        top_buf_1_d0,
        top_buf_2_address0,
        top_buf_2_ce0,
        top_buf_2_we0,
        top_buf_2_d0,
        top_buf_3_address0,
        top_buf_3_ce0,
        top_buf_3_we0,
        top_buf_3_d0,
        top_buf_4_address0,
        top_buf_4_ce0,
        top_buf_4_we0,
        top_buf_4_d0,
        top_buf_5_address0,
        top_buf_5_ce0,
        top_buf_5_we0,
        top_buf_5_d0,
        top_buf_6_address0,
        top_buf_6_ce0,
        top_buf_6_we0,
        top_buf_6_d0,
        top_buf_7_address0,
        top_buf_7_ce0,
        top_buf_7_we0,
        top_buf_7_d0,
        top_buf_8_address0,
        top_buf_8_ce0,
        top_buf_8_we0,
        top_buf_8_d0,
        top_buf_9_address0,
        top_buf_9_ce0,
        top_buf_9_we0,
        top_buf_9_d0,
        top_buf_10_address0,
        top_buf_10_ce0,
        top_buf_10_we0,
        top_buf_10_d0,
        top_buf_11_address0,
        top_buf_11_ce0,
        top_buf_11_we0,
        top_buf_11_d0,
        top_buf_12_address0,
        top_buf_12_ce0,
        top_buf_12_we0,
        top_buf_12_d0,
        top_buf_13_address0,
        top_buf_13_ce0,
        top_buf_13_we0,
        top_buf_13_d0,
        top_buf_14_address0,
        top_buf_14_ce0,
        top_buf_14_we0,
        top_buf_14_d0,
        top_buf_15_address0,
        top_buf_15_ce0,
        top_buf_15_we0,
        top_buf_15_d0,
        bottom_buf_0_address0,
        bottom_buf_0_ce0,
        bottom_buf_0_we0,
        bottom_buf_0_d0,
        bottom_buf_1_address0,
        bottom_buf_1_ce0,
        bottom_buf_1_we0,
        bottom_buf_1_d0,
        bottom_buf_2_address0,
        bottom_buf_2_ce0,
        bottom_buf_2_we0,
        bottom_buf_2_d0,
        bottom_buf_3_address0,
        bottom_buf_3_ce0,
        bottom_buf_3_we0,
        bottom_buf_3_d0,
        bottom_buf_4_address0,
        bottom_buf_4_ce0,
        bottom_buf_4_we0,
        bottom_buf_4_d0,
        bottom_buf_5_address0,
        bottom_buf_5_ce0,
        bottom_buf_5_we0,
        bottom_buf_5_d0,
        bottom_buf_6_address0,
        bottom_buf_6_ce0,
        bottom_buf_6_we0,
        bottom_buf_6_d0,
        bottom_buf_7_address0,
        bottom_buf_7_ce0,
        bottom_buf_7_we0,
        bottom_buf_7_d0,
        bottom_buf_8_address0,
        bottom_buf_8_ce0,
        bottom_buf_8_we0,
        bottom_buf_8_d0,
        bottom_buf_9_address0,
        bottom_buf_9_ce0,
        bottom_buf_9_we0,
        bottom_buf_9_d0,
        bottom_buf_10_address0,
        bottom_buf_10_ce0,
        bottom_buf_10_we0,
        bottom_buf_10_d0,
        bottom_buf_11_address0,
        bottom_buf_11_ce0,
        bottom_buf_11_we0,
        bottom_buf_11_d0,
        bottom_buf_12_address0,
        bottom_buf_12_ce0,
        bottom_buf_12_we0,
        bottom_buf_12_d0,
        bottom_buf_13_address0,
        bottom_buf_13_ce0,
        bottom_buf_13_we0,
        bottom_buf_13_d0,
        bottom_buf_14_address0,
        bottom_buf_14_ce0,
        bottom_buf_14_we0,
        bottom_buf_14_d0,
        bottom_buf_15_address0,
        bottom_buf_15_ce0,
        bottom_buf_15_we0,
        bottom_buf_15_d0,
        layer
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] temp_address0;
output   temp_ce0;
input  [511:0] temp_q0;
input  [0:0] load_flag;
output  [7:0] center_buf_0_address0;
output   center_buf_0_ce0;
output   center_buf_0_we0;
output  [31:0] center_buf_0_d0;
output  [7:0] center_buf_1_address0;
output   center_buf_1_ce0;
output   center_buf_1_we0;
output  [31:0] center_buf_1_d0;
output  [7:0] center_buf_2_address0;
output   center_buf_2_ce0;
output   center_buf_2_we0;
output  [31:0] center_buf_2_d0;
output  [7:0] center_buf_3_address0;
output   center_buf_3_ce0;
output   center_buf_3_we0;
output  [31:0] center_buf_3_d0;
output  [7:0] center_buf_4_address0;
output   center_buf_4_ce0;
output   center_buf_4_we0;
output  [31:0] center_buf_4_d0;
output  [7:0] center_buf_5_address0;
output   center_buf_5_ce0;
output   center_buf_5_we0;
output  [31:0] center_buf_5_d0;
output  [7:0] center_buf_6_address0;
output   center_buf_6_ce0;
output   center_buf_6_we0;
output  [31:0] center_buf_6_d0;
output  [7:0] center_buf_7_address0;
output   center_buf_7_ce0;
output   center_buf_7_we0;
output  [31:0] center_buf_7_d0;
output  [7:0] center_buf_8_address0;
output   center_buf_8_ce0;
output   center_buf_8_we0;
output  [31:0] center_buf_8_d0;
output  [7:0] center_buf_9_address0;
output   center_buf_9_ce0;
output   center_buf_9_we0;
output  [31:0] center_buf_9_d0;
output  [7:0] center_buf_10_address0;
output   center_buf_10_ce0;
output   center_buf_10_we0;
output  [31:0] center_buf_10_d0;
output  [7:0] center_buf_11_address0;
output   center_buf_11_ce0;
output   center_buf_11_we0;
output  [31:0] center_buf_11_d0;
output  [7:0] center_buf_12_address0;
output   center_buf_12_ce0;
output   center_buf_12_we0;
output  [31:0] center_buf_12_d0;
output  [7:0] center_buf_13_address0;
output   center_buf_13_ce0;
output   center_buf_13_we0;
output  [31:0] center_buf_13_d0;
output  [7:0] center_buf_14_address0;
output   center_buf_14_ce0;
output   center_buf_14_we0;
output  [31:0] center_buf_14_d0;
output  [7:0] center_buf_15_address0;
output   center_buf_15_ce0;
output   center_buf_15_we0;
output  [31:0] center_buf_15_d0;
output  [7:0] top_buf_0_address0;
output   top_buf_0_ce0;
output   top_buf_0_we0;
output  [31:0] top_buf_0_d0;
output  [7:0] top_buf_1_address0;
output   top_buf_1_ce0;
output   top_buf_1_we0;
output  [31:0] top_buf_1_d0;
output  [7:0] top_buf_2_address0;
output   top_buf_2_ce0;
output   top_buf_2_we0;
output  [31:0] top_buf_2_d0;
output  [7:0] top_buf_3_address0;
output   top_buf_3_ce0;
output   top_buf_3_we0;
output  [31:0] top_buf_3_d0;
output  [7:0] top_buf_4_address0;
output   top_buf_4_ce0;
output   top_buf_4_we0;
output  [31:0] top_buf_4_d0;
output  [7:0] top_buf_5_address0;
output   top_buf_5_ce0;
output   top_buf_5_we0;
output  [31:0] top_buf_5_d0;
output  [7:0] top_buf_6_address0;
output   top_buf_6_ce0;
output   top_buf_6_we0;
output  [31:0] top_buf_6_d0;
output  [7:0] top_buf_7_address0;
output   top_buf_7_ce0;
output   top_buf_7_we0;
output  [31:0] top_buf_7_d0;
output  [7:0] top_buf_8_address0;
output   top_buf_8_ce0;
output   top_buf_8_we0;
output  [31:0] top_buf_8_d0;
output  [7:0] top_buf_9_address0;
output   top_buf_9_ce0;
output   top_buf_9_we0;
output  [31:0] top_buf_9_d0;
output  [7:0] top_buf_10_address0;
output   top_buf_10_ce0;
output   top_buf_10_we0;
output  [31:0] top_buf_10_d0;
output  [7:0] top_buf_11_address0;
output   top_buf_11_ce0;
output   top_buf_11_we0;
output  [31:0] top_buf_11_d0;
output  [7:0] top_buf_12_address0;
output   top_buf_12_ce0;
output   top_buf_12_we0;
output  [31:0] top_buf_12_d0;
output  [7:0] top_buf_13_address0;
output   top_buf_13_ce0;
output   top_buf_13_we0;
output  [31:0] top_buf_13_d0;
output  [7:0] top_buf_14_address0;
output   top_buf_14_ce0;
output   top_buf_14_we0;
output  [31:0] top_buf_14_d0;
output  [7:0] top_buf_15_address0;
output   top_buf_15_ce0;
output   top_buf_15_we0;
output  [31:0] top_buf_15_d0;
output  [7:0] bottom_buf_0_address0;
output   bottom_buf_0_ce0;
output   bottom_buf_0_we0;
output  [31:0] bottom_buf_0_d0;
output  [7:0] bottom_buf_1_address0;
output   bottom_buf_1_ce0;
output   bottom_buf_1_we0;
output  [31:0] bottom_buf_1_d0;
output  [7:0] bottom_buf_2_address0;
output   bottom_buf_2_ce0;
output   bottom_buf_2_we0;
output  [31:0] bottom_buf_2_d0;
output  [7:0] bottom_buf_3_address0;
output   bottom_buf_3_ce0;
output   bottom_buf_3_we0;
output  [31:0] bottom_buf_3_d0;
output  [7:0] bottom_buf_4_address0;
output   bottom_buf_4_ce0;
output   bottom_buf_4_we0;
output  [31:0] bottom_buf_4_d0;
output  [7:0] bottom_buf_5_address0;
output   bottom_buf_5_ce0;
output   bottom_buf_5_we0;
output  [31:0] bottom_buf_5_d0;
output  [7:0] bottom_buf_6_address0;
output   bottom_buf_6_ce0;
output   bottom_buf_6_we0;
output  [31:0] bottom_buf_6_d0;
output  [7:0] bottom_buf_7_address0;
output   bottom_buf_7_ce0;
output   bottom_buf_7_we0;
output  [31:0] bottom_buf_7_d0;
output  [7:0] bottom_buf_8_address0;
output   bottom_buf_8_ce0;
output   bottom_buf_8_we0;
output  [31:0] bottom_buf_8_d0;
output  [7:0] bottom_buf_9_address0;
output   bottom_buf_9_ce0;
output   bottom_buf_9_we0;
output  [31:0] bottom_buf_9_d0;
output  [7:0] bottom_buf_10_address0;
output   bottom_buf_10_ce0;
output   bottom_buf_10_we0;
output  [31:0] bottom_buf_10_d0;
output  [7:0] bottom_buf_11_address0;
output   bottom_buf_11_ce0;
output   bottom_buf_11_we0;
output  [31:0] bottom_buf_11_d0;
output  [7:0] bottom_buf_12_address0;
output   bottom_buf_12_ce0;
output   bottom_buf_12_we0;
output  [31:0] bottom_buf_12_d0;
output  [7:0] bottom_buf_13_address0;
output   bottom_buf_13_ce0;
output   bottom_buf_13_we0;
output  [31:0] bottom_buf_13_d0;
output  [7:0] bottom_buf_14_address0;
output   bottom_buf_14_ce0;
output   bottom_buf_14_we0;
output  [31:0] bottom_buf_14_d0;
output  [7:0] bottom_buf_15_address0;
output   bottom_buf_15_ce0;
output   bottom_buf_15_we0;
output  [31:0] bottom_buf_15_d0;
input  [3:0] layer;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg temp_ce0;
reg center_buf_0_ce0;
reg center_buf_0_we0;
reg center_buf_1_ce0;
reg center_buf_1_we0;
reg center_buf_2_ce0;
reg center_buf_2_we0;
reg center_buf_3_ce0;
reg center_buf_3_we0;
reg center_buf_4_ce0;
reg center_buf_4_we0;
reg center_buf_5_ce0;
reg center_buf_5_we0;
reg center_buf_6_ce0;
reg center_buf_6_we0;
reg center_buf_7_ce0;
reg center_buf_7_we0;
reg center_buf_8_ce0;
reg center_buf_8_we0;
reg center_buf_9_ce0;
reg center_buf_9_we0;
reg center_buf_10_ce0;
reg center_buf_10_we0;
reg center_buf_11_ce0;
reg center_buf_11_we0;
reg center_buf_12_ce0;
reg center_buf_12_we0;
reg center_buf_13_ce0;
reg center_buf_13_we0;
reg center_buf_14_ce0;
reg center_buf_14_we0;
reg center_buf_15_ce0;
reg center_buf_15_we0;
reg top_buf_0_ce0;
reg top_buf_0_we0;
reg top_buf_1_ce0;
reg top_buf_1_we0;
reg top_buf_2_ce0;
reg top_buf_2_we0;
reg top_buf_3_ce0;
reg top_buf_3_we0;
reg top_buf_4_ce0;
reg top_buf_4_we0;
reg top_buf_5_ce0;
reg top_buf_5_we0;
reg top_buf_6_ce0;
reg top_buf_6_we0;
reg top_buf_7_ce0;
reg top_buf_7_we0;
reg top_buf_8_ce0;
reg top_buf_8_we0;
reg top_buf_9_ce0;
reg top_buf_9_we0;
reg top_buf_10_ce0;
reg top_buf_10_we0;
reg top_buf_11_ce0;
reg top_buf_11_we0;
reg top_buf_12_ce0;
reg top_buf_12_we0;
reg top_buf_13_ce0;
reg top_buf_13_we0;
reg top_buf_14_ce0;
reg top_buf_14_we0;
reg top_buf_15_ce0;
reg top_buf_15_we0;
reg bottom_buf_0_ce0;
reg bottom_buf_0_we0;
reg bottom_buf_1_ce0;
reg bottom_buf_1_we0;
reg bottom_buf_2_ce0;
reg bottom_buf_2_we0;
reg bottom_buf_3_ce0;
reg bottom_buf_3_we0;
reg bottom_buf_4_ce0;
reg bottom_buf_4_we0;
reg bottom_buf_5_ce0;
reg bottom_buf_5_we0;
reg bottom_buf_6_ce0;
reg bottom_buf_6_we0;
reg bottom_buf_7_ce0;
reg bottom_buf_7_we0;
reg bottom_buf_8_ce0;
reg bottom_buf_8_we0;
reg bottom_buf_9_ce0;
reg bottom_buf_9_we0;
reg bottom_buf_10_ce0;
reg bottom_buf_10_we0;
reg bottom_buf_11_ce0;
reg bottom_buf_11_we0;
reg bottom_buf_12_ce0;
reg bottom_buf_12_we0;
reg bottom_buf_13_ce0;
reg bottom_buf_13_we0;
reg bottom_buf_14_ce0;
reg bottom_buf_14_we0;
reg bottom_buf_15_ce0;
reg bottom_buf_15_we0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [20:0] zext_ln247_1_fu_259_p1;
reg   [20:0] zext_ln247_1_reg_384;
wire   [20:0] zext_ln248_fu_299_p1;
reg   [20:0] zext_ln248_reg_389;
wire    ap_CS_fsm_state12;
wire   [12:0] select_ln249_fu_354_p3;
reg   [12:0] select_ln249_reg_394;
wire  signed [20:0] sext_ln249_1_fu_369_p1;
reg  signed [20:0] sext_ln249_1_reg_399;
wire    ap_CS_fsm_state14;
wire    grp_buffer_load_fu_174_ap_start;
wire    grp_buffer_load_fu_174_ap_done;
wire    grp_buffer_load_fu_174_ap_idle;
wire    grp_buffer_load_fu_174_ap_ready;
wire   [14:0] grp_buffer_load_fu_174_temp_address0;
wire    grp_buffer_load_fu_174_temp_ce0;
wire   [7:0] grp_buffer_load_fu_174_dest_0_address0;
wire    grp_buffer_load_fu_174_dest_0_ce0;
wire    grp_buffer_load_fu_174_dest_0_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_0_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_1_address0;
wire    grp_buffer_load_fu_174_dest_1_ce0;
wire    grp_buffer_load_fu_174_dest_1_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_1_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_2_address0;
wire    grp_buffer_load_fu_174_dest_2_ce0;
wire    grp_buffer_load_fu_174_dest_2_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_2_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_3_address0;
wire    grp_buffer_load_fu_174_dest_3_ce0;
wire    grp_buffer_load_fu_174_dest_3_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_3_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_4_address0;
wire    grp_buffer_load_fu_174_dest_4_ce0;
wire    grp_buffer_load_fu_174_dest_4_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_4_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_5_address0;
wire    grp_buffer_load_fu_174_dest_5_ce0;
wire    grp_buffer_load_fu_174_dest_5_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_5_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_6_address0;
wire    grp_buffer_load_fu_174_dest_6_ce0;
wire    grp_buffer_load_fu_174_dest_6_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_6_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_7_address0;
wire    grp_buffer_load_fu_174_dest_7_ce0;
wire    grp_buffer_load_fu_174_dest_7_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_7_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_8_address0;
wire    grp_buffer_load_fu_174_dest_8_ce0;
wire    grp_buffer_load_fu_174_dest_8_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_8_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_9_address0;
wire    grp_buffer_load_fu_174_dest_9_ce0;
wire    grp_buffer_load_fu_174_dest_9_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_9_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_10_address0;
wire    grp_buffer_load_fu_174_dest_10_ce0;
wire    grp_buffer_load_fu_174_dest_10_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_10_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_11_address0;
wire    grp_buffer_load_fu_174_dest_11_ce0;
wire    grp_buffer_load_fu_174_dest_11_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_11_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_12_address0;
wire    grp_buffer_load_fu_174_dest_12_ce0;
wire    grp_buffer_load_fu_174_dest_12_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_12_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_13_address0;
wire    grp_buffer_load_fu_174_dest_13_ce0;
wire    grp_buffer_load_fu_174_dest_13_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_13_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_14_address0;
wire    grp_buffer_load_fu_174_dest_14_ce0;
wire    grp_buffer_load_fu_174_dest_14_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_14_d0;
wire   [7:0] grp_buffer_load_fu_174_dest_15_address0;
wire    grp_buffer_load_fu_174_dest_15_ce0;
wire    grp_buffer_load_fu_174_dest_15_we0;
wire   [31:0] grp_buffer_load_fu_174_dest_15_d0;
reg   [20:0] grp_buffer_load_fu_174_source;
reg    grp_buffer_load_fu_174_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state13;
wire   [17:0] shl_ln247_1_fu_251_p3;
wire   [15:0] shl_ln_fu_264_p3;
wire   [15:0] add_ln248_fu_275_p2;
wire   [11:0] tmp_fu_281_p4;
wire   [17:0] shl_ln1_fu_291_p3;
wire   [16:0] zext_ln247_fu_271_p1;
wire   [16:0] add_ln249_fu_304_p2;
wire   [15:0] sub_ln249_fu_318_p2;
wire   [11:0] trunc_ln249_1_fu_324_p4;
wire  signed [12:0] sext_ln249_fu_334_p1;
wire   [0:0] tmp_1_fu_310_p3;
wire   [12:0] sub_ln249_1_fu_338_p2;
wire   [12:0] trunc_ln249_2_fu_344_p4;
wire   [18:0] tmp_2_fu_362_p3;
reg    ap_predicate_op32_call_state6;
reg    ap_block_state6_on_subcall_done;
reg   [13:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_buffer_load_fu_174_ap_start_reg = 1'b0;
end

hotspot_HW_buffer_load grp_buffer_load_fu_174(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_buffer_load_fu_174_ap_start),
    .ap_done(grp_buffer_load_fu_174_ap_done),
    .ap_idle(grp_buffer_load_fu_174_ap_idle),
    .ap_ready(grp_buffer_load_fu_174_ap_ready),
    .temp_address0(grp_buffer_load_fu_174_temp_address0),
    .temp_ce0(grp_buffer_load_fu_174_temp_ce0),
    .temp_q0(temp_q0),
    .load_flag(load_flag),
    .dest_0_address0(grp_buffer_load_fu_174_dest_0_address0),
    .dest_0_ce0(grp_buffer_load_fu_174_dest_0_ce0),
    .dest_0_we0(grp_buffer_load_fu_174_dest_0_we0),
    .dest_0_d0(grp_buffer_load_fu_174_dest_0_d0),
    .dest_1_address0(grp_buffer_load_fu_174_dest_1_address0),
    .dest_1_ce0(grp_buffer_load_fu_174_dest_1_ce0),
    .dest_1_we0(grp_buffer_load_fu_174_dest_1_we0),
    .dest_1_d0(grp_buffer_load_fu_174_dest_1_d0),
    .dest_2_address0(grp_buffer_load_fu_174_dest_2_address0),
    .dest_2_ce0(grp_buffer_load_fu_174_dest_2_ce0),
    .dest_2_we0(grp_buffer_load_fu_174_dest_2_we0),
    .dest_2_d0(grp_buffer_load_fu_174_dest_2_d0),
    .dest_3_address0(grp_buffer_load_fu_174_dest_3_address0),
    .dest_3_ce0(grp_buffer_load_fu_174_dest_3_ce0),
    .dest_3_we0(grp_buffer_load_fu_174_dest_3_we0),
    .dest_3_d0(grp_buffer_load_fu_174_dest_3_d0),
    .dest_4_address0(grp_buffer_load_fu_174_dest_4_address0),
    .dest_4_ce0(grp_buffer_load_fu_174_dest_4_ce0),
    .dest_4_we0(grp_buffer_load_fu_174_dest_4_we0),
    .dest_4_d0(grp_buffer_load_fu_174_dest_4_d0),
    .dest_5_address0(grp_buffer_load_fu_174_dest_5_address0),
    .dest_5_ce0(grp_buffer_load_fu_174_dest_5_ce0),
    .dest_5_we0(grp_buffer_load_fu_174_dest_5_we0),
    .dest_5_d0(grp_buffer_load_fu_174_dest_5_d0),
    .dest_6_address0(grp_buffer_load_fu_174_dest_6_address0),
    .dest_6_ce0(grp_buffer_load_fu_174_dest_6_ce0),
    .dest_6_we0(grp_buffer_load_fu_174_dest_6_we0),
    .dest_6_d0(grp_buffer_load_fu_174_dest_6_d0),
    .dest_7_address0(grp_buffer_load_fu_174_dest_7_address0),
    .dest_7_ce0(grp_buffer_load_fu_174_dest_7_ce0),
    .dest_7_we0(grp_buffer_load_fu_174_dest_7_we0),
    .dest_7_d0(grp_buffer_load_fu_174_dest_7_d0),
    .dest_8_address0(grp_buffer_load_fu_174_dest_8_address0),
    .dest_8_ce0(grp_buffer_load_fu_174_dest_8_ce0),
    .dest_8_we0(grp_buffer_load_fu_174_dest_8_we0),
    .dest_8_d0(grp_buffer_load_fu_174_dest_8_d0),
    .dest_9_address0(grp_buffer_load_fu_174_dest_9_address0),
    .dest_9_ce0(grp_buffer_load_fu_174_dest_9_ce0),
    .dest_9_we0(grp_buffer_load_fu_174_dest_9_we0),
    .dest_9_d0(grp_buffer_load_fu_174_dest_9_d0),
    .dest_10_address0(grp_buffer_load_fu_174_dest_10_address0),
    .dest_10_ce0(grp_buffer_load_fu_174_dest_10_ce0),
    .dest_10_we0(grp_buffer_load_fu_174_dest_10_we0),
    .dest_10_d0(grp_buffer_load_fu_174_dest_10_d0),
    .dest_11_address0(grp_buffer_load_fu_174_dest_11_address0),
    .dest_11_ce0(grp_buffer_load_fu_174_dest_11_ce0),
    .dest_11_we0(grp_buffer_load_fu_174_dest_11_we0),
    .dest_11_d0(grp_buffer_load_fu_174_dest_11_d0),
    .dest_12_address0(grp_buffer_load_fu_174_dest_12_address0),
    .dest_12_ce0(grp_buffer_load_fu_174_dest_12_ce0),
    .dest_12_we0(grp_buffer_load_fu_174_dest_12_we0),
    .dest_12_d0(grp_buffer_load_fu_174_dest_12_d0),
    .dest_13_address0(grp_buffer_load_fu_174_dest_13_address0),
    .dest_13_ce0(grp_buffer_load_fu_174_dest_13_ce0),
    .dest_13_we0(grp_buffer_load_fu_174_dest_13_we0),
    .dest_13_d0(grp_buffer_load_fu_174_dest_13_d0),
    .dest_14_address0(grp_buffer_load_fu_174_dest_14_address0),
    .dest_14_ce0(grp_buffer_load_fu_174_dest_14_ce0),
    .dest_14_we0(grp_buffer_load_fu_174_dest_14_we0),
    .dest_14_d0(grp_buffer_load_fu_174_dest_14_d0),
    .dest_15_address0(grp_buffer_load_fu_174_dest_15_address0),
    .dest_15_ce0(grp_buffer_load_fu_174_dest_15_ce0),
    .dest_15_we0(grp_buffer_load_fu_174_dest_15_we0),
    .dest_15_d0(grp_buffer_load_fu_174_dest_15_d0),
    .source(grp_buffer_load_fu_174_source)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_buffer_load_fu_174_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
            grp_buffer_load_fu_174_ap_start_reg <= 1'b1;
        end else if ((grp_buffer_load_fu_174_ap_ready == 1'b1)) begin
            grp_buffer_load_fu_174_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        select_ln249_reg_394[12 : 8] <= select_ln249_fu_354_p3[12 : 8];
        zext_ln248_reg_389[17 : 14] <= zext_ln248_fu_299_p1[17 : 14];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sext_ln249_1_reg_399[20 : 14] <= sext_ln249_1_fu_369_p1[20 : 14];
    end
end

always @ (posedge ap_clk) begin
    if ((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        zext_ln247_1_reg_384[17 : 14] <= zext_ln247_1_fu_259_p1[17 : 14];
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_0_ce0 = grp_buffer_load_fu_174_dest_0_ce0;
    end else begin
        bottom_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_0_we0 = grp_buffer_load_fu_174_dest_0_we0;
    end else begin
        bottom_buf_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_10_ce0 = grp_buffer_load_fu_174_dest_10_ce0;
    end else begin
        bottom_buf_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_10_we0 = grp_buffer_load_fu_174_dest_10_we0;
    end else begin
        bottom_buf_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_11_ce0 = grp_buffer_load_fu_174_dest_11_ce0;
    end else begin
        bottom_buf_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_11_we0 = grp_buffer_load_fu_174_dest_11_we0;
    end else begin
        bottom_buf_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_12_ce0 = grp_buffer_load_fu_174_dest_12_ce0;
    end else begin
        bottom_buf_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_12_we0 = grp_buffer_load_fu_174_dest_12_we0;
    end else begin
        bottom_buf_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_13_ce0 = grp_buffer_load_fu_174_dest_13_ce0;
    end else begin
        bottom_buf_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_13_we0 = grp_buffer_load_fu_174_dest_13_we0;
    end else begin
        bottom_buf_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_14_ce0 = grp_buffer_load_fu_174_dest_14_ce0;
    end else begin
        bottom_buf_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_14_we0 = grp_buffer_load_fu_174_dest_14_we0;
    end else begin
        bottom_buf_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_15_ce0 = grp_buffer_load_fu_174_dest_15_ce0;
    end else begin
        bottom_buf_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_15_we0 = grp_buffer_load_fu_174_dest_15_we0;
    end else begin
        bottom_buf_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_1_ce0 = grp_buffer_load_fu_174_dest_1_ce0;
    end else begin
        bottom_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_1_we0 = grp_buffer_load_fu_174_dest_1_we0;
    end else begin
        bottom_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_2_ce0 = grp_buffer_load_fu_174_dest_2_ce0;
    end else begin
        bottom_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_2_we0 = grp_buffer_load_fu_174_dest_2_we0;
    end else begin
        bottom_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_3_ce0 = grp_buffer_load_fu_174_dest_3_ce0;
    end else begin
        bottom_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_3_we0 = grp_buffer_load_fu_174_dest_3_we0;
    end else begin
        bottom_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_4_ce0 = grp_buffer_load_fu_174_dest_4_ce0;
    end else begin
        bottom_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_4_we0 = grp_buffer_load_fu_174_dest_4_we0;
    end else begin
        bottom_buf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_5_ce0 = grp_buffer_load_fu_174_dest_5_ce0;
    end else begin
        bottom_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_5_we0 = grp_buffer_load_fu_174_dest_5_we0;
    end else begin
        bottom_buf_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_6_ce0 = grp_buffer_load_fu_174_dest_6_ce0;
    end else begin
        bottom_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_6_we0 = grp_buffer_load_fu_174_dest_6_we0;
    end else begin
        bottom_buf_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_7_ce0 = grp_buffer_load_fu_174_dest_7_ce0;
    end else begin
        bottom_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_7_we0 = grp_buffer_load_fu_174_dest_7_we0;
    end else begin
        bottom_buf_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_8_ce0 = grp_buffer_load_fu_174_dest_8_ce0;
    end else begin
        bottom_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_8_we0 = grp_buffer_load_fu_174_dest_8_we0;
    end else begin
        bottom_buf_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_9_ce0 = grp_buffer_load_fu_174_dest_9_ce0;
    end else begin
        bottom_buf_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        bottom_buf_9_we0 = grp_buffer_load_fu_174_dest_9_we0;
    end else begin
        bottom_buf_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_0_ce0 = grp_buffer_load_fu_174_dest_0_ce0;
    end else begin
        center_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_0_we0 = grp_buffer_load_fu_174_dest_0_we0;
    end else begin
        center_buf_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_10_ce0 = grp_buffer_load_fu_174_dest_10_ce0;
    end else begin
        center_buf_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_10_we0 = grp_buffer_load_fu_174_dest_10_we0;
    end else begin
        center_buf_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_11_ce0 = grp_buffer_load_fu_174_dest_11_ce0;
    end else begin
        center_buf_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_11_we0 = grp_buffer_load_fu_174_dest_11_we0;
    end else begin
        center_buf_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_12_ce0 = grp_buffer_load_fu_174_dest_12_ce0;
    end else begin
        center_buf_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_12_we0 = grp_buffer_load_fu_174_dest_12_we0;
    end else begin
        center_buf_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_13_ce0 = grp_buffer_load_fu_174_dest_13_ce0;
    end else begin
        center_buf_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_13_we0 = grp_buffer_load_fu_174_dest_13_we0;
    end else begin
        center_buf_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_14_ce0 = grp_buffer_load_fu_174_dest_14_ce0;
    end else begin
        center_buf_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_14_we0 = grp_buffer_load_fu_174_dest_14_we0;
    end else begin
        center_buf_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_15_ce0 = grp_buffer_load_fu_174_dest_15_ce0;
    end else begin
        center_buf_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_15_we0 = grp_buffer_load_fu_174_dest_15_we0;
    end else begin
        center_buf_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_1_ce0 = grp_buffer_load_fu_174_dest_1_ce0;
    end else begin
        center_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_1_we0 = grp_buffer_load_fu_174_dest_1_we0;
    end else begin
        center_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_2_ce0 = grp_buffer_load_fu_174_dest_2_ce0;
    end else begin
        center_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_2_we0 = grp_buffer_load_fu_174_dest_2_we0;
    end else begin
        center_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_3_ce0 = grp_buffer_load_fu_174_dest_3_ce0;
    end else begin
        center_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_3_we0 = grp_buffer_load_fu_174_dest_3_we0;
    end else begin
        center_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_4_ce0 = grp_buffer_load_fu_174_dest_4_ce0;
    end else begin
        center_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_4_we0 = grp_buffer_load_fu_174_dest_4_we0;
    end else begin
        center_buf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_5_ce0 = grp_buffer_load_fu_174_dest_5_ce0;
    end else begin
        center_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_5_we0 = grp_buffer_load_fu_174_dest_5_we0;
    end else begin
        center_buf_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_6_ce0 = grp_buffer_load_fu_174_dest_6_ce0;
    end else begin
        center_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_6_we0 = grp_buffer_load_fu_174_dest_6_we0;
    end else begin
        center_buf_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_7_ce0 = grp_buffer_load_fu_174_dest_7_ce0;
    end else begin
        center_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_7_we0 = grp_buffer_load_fu_174_dest_7_we0;
    end else begin
        center_buf_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_8_ce0 = grp_buffer_load_fu_174_dest_8_ce0;
    end else begin
        center_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_8_we0 = grp_buffer_load_fu_174_dest_8_we0;
    end else begin
        center_buf_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_9_ce0 = grp_buffer_load_fu_174_dest_9_ce0;
    end else begin
        center_buf_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        center_buf_9_we0 = grp_buffer_load_fu_174_dest_9_we0;
    end else begin
        center_buf_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_buffer_load_fu_174_source = sext_ln249_1_reg_399;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_buffer_load_fu_174_source = zext_ln248_reg_389;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_buffer_load_fu_174_source = 21'd16384;
    end else if (((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_buffer_load_fu_174_source = 21'd98304;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_buffer_load_fu_174_source = zext_ln247_1_reg_384;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_buffer_load_fu_174_source = 21'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_buffer_load_fu_174_source = 21'd114688;
    end else begin
        grp_buffer_load_fu_174_source = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2) | (~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd7) & (1'b1 == ap_CS_fsm_state6)) | ((layer == 4'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        temp_ce0 = grp_buffer_load_fu_174_temp_ce0;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_0_ce0 = grp_buffer_load_fu_174_dest_0_ce0;
    end else begin
        top_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_0_we0 = grp_buffer_load_fu_174_dest_0_we0;
    end else begin
        top_buf_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_10_ce0 = grp_buffer_load_fu_174_dest_10_ce0;
    end else begin
        top_buf_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_10_we0 = grp_buffer_load_fu_174_dest_10_we0;
    end else begin
        top_buf_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_11_ce0 = grp_buffer_load_fu_174_dest_11_ce0;
    end else begin
        top_buf_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_11_we0 = grp_buffer_load_fu_174_dest_11_we0;
    end else begin
        top_buf_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_12_ce0 = grp_buffer_load_fu_174_dest_12_ce0;
    end else begin
        top_buf_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_12_we0 = grp_buffer_load_fu_174_dest_12_we0;
    end else begin
        top_buf_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_13_ce0 = grp_buffer_load_fu_174_dest_13_ce0;
    end else begin
        top_buf_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_13_we0 = grp_buffer_load_fu_174_dest_13_we0;
    end else begin
        top_buf_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_14_ce0 = grp_buffer_load_fu_174_dest_14_ce0;
    end else begin
        top_buf_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_14_we0 = grp_buffer_load_fu_174_dest_14_we0;
    end else begin
        top_buf_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_15_ce0 = grp_buffer_load_fu_174_dest_15_ce0;
    end else begin
        top_buf_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_15_we0 = grp_buffer_load_fu_174_dest_15_we0;
    end else begin
        top_buf_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_1_ce0 = grp_buffer_load_fu_174_dest_1_ce0;
    end else begin
        top_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_1_we0 = grp_buffer_load_fu_174_dest_1_we0;
    end else begin
        top_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_2_ce0 = grp_buffer_load_fu_174_dest_2_ce0;
    end else begin
        top_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_2_we0 = grp_buffer_load_fu_174_dest_2_we0;
    end else begin
        top_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_3_ce0 = grp_buffer_load_fu_174_dest_3_ce0;
    end else begin
        top_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_3_we0 = grp_buffer_load_fu_174_dest_3_we0;
    end else begin
        top_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_4_ce0 = grp_buffer_load_fu_174_dest_4_ce0;
    end else begin
        top_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_4_we0 = grp_buffer_load_fu_174_dest_4_we0;
    end else begin
        top_buf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_5_ce0 = grp_buffer_load_fu_174_dest_5_ce0;
    end else begin
        top_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_5_we0 = grp_buffer_load_fu_174_dest_5_we0;
    end else begin
        top_buf_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_6_ce0 = grp_buffer_load_fu_174_dest_6_ce0;
    end else begin
        top_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_6_we0 = grp_buffer_load_fu_174_dest_6_we0;
    end else begin
        top_buf_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_7_ce0 = grp_buffer_load_fu_174_dest_7_ce0;
    end else begin
        top_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_7_we0 = grp_buffer_load_fu_174_dest_7_we0;
    end else begin
        top_buf_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_8_ce0 = grp_buffer_load_fu_174_dest_8_ce0;
    end else begin
        top_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_8_we0 = grp_buffer_load_fu_174_dest_8_we0;
    end else begin
        top_buf_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_9_ce0 = grp_buffer_load_fu_174_dest_9_ce0;
    end else begin
        top_buf_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        top_buf_9_we0 = grp_buffer_load_fu_174_dest_9_we0;
    end else begin
        top_buf_9_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~(layer == 4'd7) & ~(layer == 4'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((layer == 4'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((layer == 4'd7) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_buffer_load_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_buffer_load_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_buffer_load_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_buffer_load_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_buffer_load_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_buffer_load_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln248_fu_275_p2 = (shl_ln_fu_264_p3 + 16'd4096);

assign add_ln249_fu_304_p2 = ($signed(zext_ln247_fu_271_p1) + $signed(17'd126976));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state6_on_subcall_done = (((ap_predicate_op32_call_state6 == 1'b1) & (grp_buffer_load_fu_174_ap_done == 1'b0)) | ((grp_buffer_load_fu_174_ap_done == 1'b0) & (layer == 4'd7)) | ((grp_buffer_load_fu_174_ap_done == 1'b0) & (layer == 4'd0)));
end

always @ (*) begin
    ap_predicate_op32_call_state6 = (~(layer == 4'd7) & ~(layer == 4'd0));
end

assign bottom_buf_0_address0 = grp_buffer_load_fu_174_dest_0_address0;

assign bottom_buf_0_d0 = grp_buffer_load_fu_174_dest_0_d0;

assign bottom_buf_10_address0 = grp_buffer_load_fu_174_dest_10_address0;

assign bottom_buf_10_d0 = grp_buffer_load_fu_174_dest_10_d0;

assign bottom_buf_11_address0 = grp_buffer_load_fu_174_dest_11_address0;

assign bottom_buf_11_d0 = grp_buffer_load_fu_174_dest_11_d0;

assign bottom_buf_12_address0 = grp_buffer_load_fu_174_dest_12_address0;

assign bottom_buf_12_d0 = grp_buffer_load_fu_174_dest_12_d0;

assign bottom_buf_13_address0 = grp_buffer_load_fu_174_dest_13_address0;

assign bottom_buf_13_d0 = grp_buffer_load_fu_174_dest_13_d0;

assign bottom_buf_14_address0 = grp_buffer_load_fu_174_dest_14_address0;

assign bottom_buf_14_d0 = grp_buffer_load_fu_174_dest_14_d0;

assign bottom_buf_15_address0 = grp_buffer_load_fu_174_dest_15_address0;

assign bottom_buf_15_d0 = grp_buffer_load_fu_174_dest_15_d0;

assign bottom_buf_1_address0 = grp_buffer_load_fu_174_dest_1_address0;

assign bottom_buf_1_d0 = grp_buffer_load_fu_174_dest_1_d0;

assign bottom_buf_2_address0 = grp_buffer_load_fu_174_dest_2_address0;

assign bottom_buf_2_d0 = grp_buffer_load_fu_174_dest_2_d0;

assign bottom_buf_3_address0 = grp_buffer_load_fu_174_dest_3_address0;

assign bottom_buf_3_d0 = grp_buffer_load_fu_174_dest_3_d0;

assign bottom_buf_4_address0 = grp_buffer_load_fu_174_dest_4_address0;

assign bottom_buf_4_d0 = grp_buffer_load_fu_174_dest_4_d0;

assign bottom_buf_5_address0 = grp_buffer_load_fu_174_dest_5_address0;

assign bottom_buf_5_d0 = grp_buffer_load_fu_174_dest_5_d0;

assign bottom_buf_6_address0 = grp_buffer_load_fu_174_dest_6_address0;

assign bottom_buf_6_d0 = grp_buffer_load_fu_174_dest_6_d0;

assign bottom_buf_7_address0 = grp_buffer_load_fu_174_dest_7_address0;

assign bottom_buf_7_d0 = grp_buffer_load_fu_174_dest_7_d0;

assign bottom_buf_8_address0 = grp_buffer_load_fu_174_dest_8_address0;

assign bottom_buf_8_d0 = grp_buffer_load_fu_174_dest_8_d0;

assign bottom_buf_9_address0 = grp_buffer_load_fu_174_dest_9_address0;

assign bottom_buf_9_d0 = grp_buffer_load_fu_174_dest_9_d0;

assign center_buf_0_address0 = grp_buffer_load_fu_174_dest_0_address0;

assign center_buf_0_d0 = grp_buffer_load_fu_174_dest_0_d0;

assign center_buf_10_address0 = grp_buffer_load_fu_174_dest_10_address0;

assign center_buf_10_d0 = grp_buffer_load_fu_174_dest_10_d0;

assign center_buf_11_address0 = grp_buffer_load_fu_174_dest_11_address0;

assign center_buf_11_d0 = grp_buffer_load_fu_174_dest_11_d0;

assign center_buf_12_address0 = grp_buffer_load_fu_174_dest_12_address0;

assign center_buf_12_d0 = grp_buffer_load_fu_174_dest_12_d0;

assign center_buf_13_address0 = grp_buffer_load_fu_174_dest_13_address0;

assign center_buf_13_d0 = grp_buffer_load_fu_174_dest_13_d0;

assign center_buf_14_address0 = grp_buffer_load_fu_174_dest_14_address0;

assign center_buf_14_d0 = grp_buffer_load_fu_174_dest_14_d0;

assign center_buf_15_address0 = grp_buffer_load_fu_174_dest_15_address0;

assign center_buf_15_d0 = grp_buffer_load_fu_174_dest_15_d0;

assign center_buf_1_address0 = grp_buffer_load_fu_174_dest_1_address0;

assign center_buf_1_d0 = grp_buffer_load_fu_174_dest_1_d0;

assign center_buf_2_address0 = grp_buffer_load_fu_174_dest_2_address0;

assign center_buf_2_d0 = grp_buffer_load_fu_174_dest_2_d0;

assign center_buf_3_address0 = grp_buffer_load_fu_174_dest_3_address0;

assign center_buf_3_d0 = grp_buffer_load_fu_174_dest_3_d0;

assign center_buf_4_address0 = grp_buffer_load_fu_174_dest_4_address0;

assign center_buf_4_d0 = grp_buffer_load_fu_174_dest_4_d0;

assign center_buf_5_address0 = grp_buffer_load_fu_174_dest_5_address0;

assign center_buf_5_d0 = grp_buffer_load_fu_174_dest_5_d0;

assign center_buf_6_address0 = grp_buffer_load_fu_174_dest_6_address0;

assign center_buf_6_d0 = grp_buffer_load_fu_174_dest_6_d0;

assign center_buf_7_address0 = grp_buffer_load_fu_174_dest_7_address0;

assign center_buf_7_d0 = grp_buffer_load_fu_174_dest_7_d0;

assign center_buf_8_address0 = grp_buffer_load_fu_174_dest_8_address0;

assign center_buf_8_d0 = grp_buffer_load_fu_174_dest_8_d0;

assign center_buf_9_address0 = grp_buffer_load_fu_174_dest_9_address0;

assign center_buf_9_d0 = grp_buffer_load_fu_174_dest_9_d0;

assign grp_buffer_load_fu_174_ap_start = grp_buffer_load_fu_174_ap_start_reg;

assign select_ln249_fu_354_p3 = ((tmp_1_fu_310_p3[0:0] == 1'b1) ? sub_ln249_1_fu_338_p2 : trunc_ln249_2_fu_344_p4);

assign sext_ln249_1_fu_369_p1 = $signed(tmp_2_fu_362_p3);

assign sext_ln249_fu_334_p1 = $signed(trunc_ln249_1_fu_324_p4);

assign shl_ln1_fu_291_p3 = {{tmp_fu_281_p4}, {6'd0}};

assign shl_ln247_1_fu_251_p3 = {{layer}, {14'd0}};

assign shl_ln_fu_264_p3 = {{layer}, {12'd0}};

assign sub_ln249_1_fu_338_p2 = ($signed(13'd0) - $signed(sext_ln249_fu_334_p1));

assign sub_ln249_fu_318_p2 = (16'd4096 - shl_ln_fu_264_p3);

assign temp_address0 = grp_buffer_load_fu_174_temp_address0;

assign tmp_1_fu_310_p3 = add_ln249_fu_304_p2[32'd16];

assign tmp_2_fu_362_p3 = {{select_ln249_reg_394}, {6'd0}};

assign tmp_fu_281_p4 = {{add_ln248_fu_275_p2[15:4]}};

assign top_buf_0_address0 = grp_buffer_load_fu_174_dest_0_address0;

assign top_buf_0_d0 = grp_buffer_load_fu_174_dest_0_d0;

assign top_buf_10_address0 = grp_buffer_load_fu_174_dest_10_address0;

assign top_buf_10_d0 = grp_buffer_load_fu_174_dest_10_d0;

assign top_buf_11_address0 = grp_buffer_load_fu_174_dest_11_address0;

assign top_buf_11_d0 = grp_buffer_load_fu_174_dest_11_d0;

assign top_buf_12_address0 = grp_buffer_load_fu_174_dest_12_address0;

assign top_buf_12_d0 = grp_buffer_load_fu_174_dest_12_d0;

assign top_buf_13_address0 = grp_buffer_load_fu_174_dest_13_address0;

assign top_buf_13_d0 = grp_buffer_load_fu_174_dest_13_d0;

assign top_buf_14_address0 = grp_buffer_load_fu_174_dest_14_address0;

assign top_buf_14_d0 = grp_buffer_load_fu_174_dest_14_d0;

assign top_buf_15_address0 = grp_buffer_load_fu_174_dest_15_address0;

assign top_buf_15_d0 = grp_buffer_load_fu_174_dest_15_d0;

assign top_buf_1_address0 = grp_buffer_load_fu_174_dest_1_address0;

assign top_buf_1_d0 = grp_buffer_load_fu_174_dest_1_d0;

assign top_buf_2_address0 = grp_buffer_load_fu_174_dest_2_address0;

assign top_buf_2_d0 = grp_buffer_load_fu_174_dest_2_d0;

assign top_buf_3_address0 = grp_buffer_load_fu_174_dest_3_address0;

assign top_buf_3_d0 = grp_buffer_load_fu_174_dest_3_d0;

assign top_buf_4_address0 = grp_buffer_load_fu_174_dest_4_address0;

assign top_buf_4_d0 = grp_buffer_load_fu_174_dest_4_d0;

assign top_buf_5_address0 = grp_buffer_load_fu_174_dest_5_address0;

assign top_buf_5_d0 = grp_buffer_load_fu_174_dest_5_d0;

assign top_buf_6_address0 = grp_buffer_load_fu_174_dest_6_address0;

assign top_buf_6_d0 = grp_buffer_load_fu_174_dest_6_d0;

assign top_buf_7_address0 = grp_buffer_load_fu_174_dest_7_address0;

assign top_buf_7_d0 = grp_buffer_load_fu_174_dest_7_d0;

assign top_buf_8_address0 = grp_buffer_load_fu_174_dest_8_address0;

assign top_buf_8_d0 = grp_buffer_load_fu_174_dest_8_d0;

assign top_buf_9_address0 = grp_buffer_load_fu_174_dest_9_address0;

assign top_buf_9_d0 = grp_buffer_load_fu_174_dest_9_d0;

assign trunc_ln249_1_fu_324_p4 = {{sub_ln249_fu_318_p2[15:4]}};

assign trunc_ln249_2_fu_344_p4 = {{add_ln249_fu_304_p2[16:4]}};

assign zext_ln247_1_fu_259_p1 = shl_ln247_1_fu_251_p3;

assign zext_ln247_fu_271_p1 = shl_ln_fu_264_p3;

assign zext_ln248_fu_299_p1 = shl_ln1_fu_291_p3;

always @ (posedge ap_clk) begin
    zext_ln247_1_reg_384[13:0] <= 14'b00000000000000;
    zext_ln247_1_reg_384[20:18] <= 3'b000;
    zext_ln248_reg_389[13:0] <= 14'b00000000000000;
    zext_ln248_reg_389[20:18] <= 3'b000;
    select_ln249_reg_394[7:0] <= 8'b00000000;
    sext_ln249_1_reg_399[13:0] <= 14'b00000000000000;
end

endmodule //hotspot_HW_selectLayer
